#NOTE: This is an internal implementation file, its format can be changed without prior notice.
#Mon Sep 03 13:49:02 CDT 2012
maven-metadata-central.xml.lastUpdated=1346698142518
maven-metadata-spring-roo-repository.xml.lastUpdated=1346698142455
maven-metadata-spring-maven-release.xml.lastUpdated=1346698142502
maven-metadata-spring-maven-milestone.xml.lastUpdated=1346698142611
maven-metadata-spring-roo-repository.xml.error=
