#NOTE: This is an internal implementation file, its format can be changed without prior notice.
#Mon Sep 03 13:49:19 CDT 2012
maven-metadata-central.xml.lastUpdated=1346698159335
maven-metadata-spring-roo-repository.xml.lastUpdated=1346698159381
maven-metadata-spring-maven-release.xml.lastUpdated=1346698159647
maven-metadata-spring-maven-milestone.xml.lastUpdated=1346698159584
maven-metadata-spring-roo-repository.xml.error=
