#NOTE: This is an internal implementation file, its format can be changed without prior notice.
#Mon Sep 03 13:49:48 CDT 2012
maven-metadata-central.xml.lastUpdated=1346698187976
maven-metadata-spring-roo-repository.xml.lastUpdated=1346698187976
maven-metadata-spring-maven-release.xml.lastUpdated=1346698187976
maven-metadata-spring-maven-milestone.xml.lastUpdated=1346698188148
maven-metadata-spring-roo-repository.xml.error=
