#NOTE: This is an internal implementation file, its format can be changed without prior notice.
#Mon Sep 03 13:49:48 CDT 2012
maven-metadata-central.xml.lastUpdated=1346698188382
maven-metadata-spring-roo-repository.xml.lastUpdated=1346698188460
maven-metadata-spring-maven-release.xml.lastUpdated=1346698188507
maven-metadata-spring-maven-milestone.xml.lastUpdated=1346698188475
maven-metadata-spring-roo-repository.xml.error=
